### ISSUE TITLE
Serverless Functions don't clone down

### ISSUE THREAD

**Issue by jovermier** [nhost/cli#356]
When running `nhost init --remote` the functions directory does not clone down. The package.json and tsconfig.json files are also missing.

**Comment by elitan** [comment]
Will we ever (reasonably) be able to do this @elephant3? If not, I suggest we close this issue using "Closed as not planned".

**Comment by elephant3** [comment]
> Will we ever (reasonably) be able to do this @elephant3? If not, I suggest we close this issue using "Closed as not planned".

@elitan cloning the functions from user's GitHub repo should be possible but as you know our `nhost init --remote` mutates the remote state of migrations, so I'm afraid people would confuse it with behaviour like in `git clone...` and break their migrations unintentionally when called more than once. Instead maybe we can rethink the logic in `nhost init --remote` and do instead:
- git clone ... (we know the repo and the branch which needs to be cloned)
- link the cloned repo to remote nhost app with `nhost link`
- pull environment variables from nhost (because this isn't stored in git)

Remote migrations state will still have to be changed in case a customer creates nhost app, links GitHub repo without any migrations and clicked around in dashboard to create tables and put data. But otherwise if migrations are already in git repo, then our cli shouldn't do anything with remote migrations state.

WDYT @elitan?

**Comment by elitan** [comment]
No, we shouldn't clone the repo. That people can do on their own using Git.

I was thinking of cloning the functions from our infra. But because we're bundling functions it does not make sense. So I'll close this issue for now.
