### ISSUE TITLE
Ability to clone the prod DB to local env

### ISSUE THREAD

**Issue by kratam** [nhost/cli#395]
It would be great to backup & restore the prod DB to my local env with just a single command (e.g. `nhost clone-db`).
Or at least give a hint on how to do it. I've tried `pg_dump` and `pg_restore` but something always breaks (hasura cannot access `hdb_catalog`, `nhost_auth_admin` cannot access `auth`, etc).

**Comment by marcusrohden** [comment]
I support this. It would be an amazing feature!
I had to recreate my cloud env twice before.

**Comment by Rigel772** [comment]
Did you try this?
https://github.com/nhost/cli/issues/227#issuecomment-1298554205

**Comment by dbarrosop** [comment]
Apologies for the super late response.

While the CLI doesn't do it automatically you can do this already. You could do something like:

```
pg_dump --data-only --file=nhost/seeds/prod.sql $conn_str
```

Just make sure you add it to `.gitignore`. Let me know if it doesn't work.

**Comment by Salman9000** [comment]
Pulling my hairs over this because it doesnt work. It is not as simple as running one pg_dump command and pg_restore command. Please nhost, you guys need to give a documentation to this as this is such a crucial feature.

I am deploying my local development environment to amazon so that I can give my test mobile application to my testing team. I need to clone the production db to my local db but there is no specific way. pg_dump/pg_restore just doesnt work.

**Comment by dbarrosop** [comment]
Given you are self-hosting that might be an issue with your self-hosted instance. What error are you getting. `pg_dump`/`pg_restore` certainly works or I am sure a lot of people would be mad at Postgres :)

**Comment by Salman9000** [comment]
I followed Nuno Patos' guide on discord. Basically, doing pg_dump bymyself was causing alot of issues. I simply downloaded the backup from nhost since I am on pro plan, and then did pg restore `pg_restore -h localhost -p 5432 -d local -U postgres data_backup` where data_backup is my backup file which i downloaded. Ran this command a couple of times and my data got restored.
