### ISSUE TITLE
Race condition between seed and graphite startup reverts hasura function tracking of auto embedding configuration

### ISSUE THREAD

**Issue by juicygoose** [nhost/cli#878]
When we are planting a seed , we often end up with a discrepancy in metadata on graphite auto-embeddings functions tracking, creating a diff locally :
<img width="680" alt="image" src="https://github.com/nhost/cli/assets/15606243/fbf7eef4-a91f-4aea-a17e-473b6b27e8c7">

It seems linked to a race condition between the SQL injection and the startup of graphite that probably doesn't have all the data to properly enforce hasura functions metadata 
Discord thread here : https://discord.com/channels/552499021260914688/1243558765098434772

Would it be possible to only startup graphite after the seed is planted ?

**Comment by dbarrosop** [comment]
Actually that's not the issue. I think the issue is two-fold:

1. The seeds are applied after the metadata
2. When the metadata is applied the objects managed by graphite don't exist yet and sometimes, only sometimes, the metadata "gets stuck" and it isn't fixed with the restart that happens a bit later (which was done precisely to fix this)

I am not sure why the restart doesn't fix it sometimes but I suspect that's a hasura issue. Anyway, I opened a PR with what I think should avoid this issue. Would you mind testing?

Head to https://github.com/nhost/cli/actions/runs/9287530440 and:

1. Download the docker image for your architecture
2. Unzip image with `unzip $file`. For instance `unzip cli-docker-image-ed9ae89eb469b35a499bbc8d3fe14cb06d041927-linux-arm64.zip`
3. `docker load < result && rm result`
4. Unzip binary with `unzip $file`. For instance `unzip cli-ed9ae89eb469b35a499bbc8d3fe14cb06d041927-darwin-arm64.zip`
5. `chmod +x nhost-cli`

Then try to use this one instead of the globally installed cli. For instance `~/Downloads/nhost-cli up`

Let me know if the issue is consistently gone.

Thanks!

**Comment by dbarrosop** [comment]
I am closing this one due to inactivity. If this is still a problem, let us know.
